apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: my-daemonset
spec:
  selector:
    matchLabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
      - name: nginx-daemonset
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-daemonset-svc
spec:
  type: NodePort
  selector:
    app: my-daemonset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # You can set a specific nodePort or let Kubernetes auto-assign it

