apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gensogram-cluster-admin-binding
subjects:
- kind: User
  name: gensogram        # Kubernetes username mapped from IAM user gensogram
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin    # Grants full cluster-wide permissions
  apiGroup: rbac.authorization.k8s.io

